### ISSUE TITLE
Can not work with RGBA, it only work RGB?

### ISSUE THREAD

**Issue by idev3105** [experience-ml/cartoonize#14]

**Comment by idev3105** [comment]
![Screenshot from 2021-07-16 10-58-42](https://user-images.githubusercontent.com/43769484/125889733-2d64f494-03b5-4af8-9f07-d6ae34220190.png)

**Comment by nirajpandkar** [comment]
Sorry for the late reply! Could you elaborate on where this problem has been encountered?

If you are feeding an image to the web app, it should take care of the conversion here - https://github.com/experience-ml/cartoonize/blob/master/app.py#L57. It's one of the model's constraints I gather.

Keeping @tjdevWorks  in the loop.

**Comment by tjdevWorks** [comment]
That's right @nirajpandkar, the model input constraints require it the input to be a RGB image.
