### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by rcgopi100** [experience-ml/cartoonize#15]
Hi,

I was trying to run and check the code Google Colab and getting the error as below.

File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)

Please check this issue on the link.
https://colab.research.google.com/drive/1tldmcOlzwbzjG3YGH5LPZGGvEytnZwBR?usp=sharing

**Comment by nirajpandkar** [comment]
Sorry for such a late reply. But better late than never :)

The error in question here relates to the port address being already used. So I suspect the application didn't exit gracefully on the port you mentioned. Try changing the port here - https://github.com/experience-ml/cartoonize/blob/master/app.py#L178.

Let me know how it goes :)
