### ISSUE TITLE
Full Video Problems!!

### ISSUE THREAD

**Issue by jaserres** [experience-ml/cartoonize#4]
Can't Process Full Video changing the code in app.py to:

os.system("ffmpeg -hide_banner -loglevel warning -ss 0 -i '{}' -filter:v scale={}:-2 -r 15 -c:a copy '{}'".format(os.path.abspath(original_video_path), width_resize, os.path.abspath(modified_video_path)))

what else I need to do?

THANKS FROM COLOMBIA!!!

**Comment by tjdevWorks** [comment]
First, please pull the updated repository code.

For processing full video set the following keys in ```config.yaml```

```yaml
trim-video: false
```
Additionally if you **don't** want your output video frame rate to be set to the ``` output_frame_rate ``` value in ``` config.yaml ```  and even **don't** want the video resized to value set in ```resize-dim ``` in ``` config.yaml ```, update the following things in the same ```config.yaml``` file.

```yaml
original_frame_rate: true
original_resolution: true
```

Kindly, please do let me know if it works for you or you face any issues.
