### ISSUE TITLE
can I  change the style of the cartoon?

### ISSUE THREAD

**Issue by TheCrowd** [experience-ml/cartoonize#6]
Can I modify the model so that the generated video is more like a Japanese cartoon?

**Comment by tjdevWorks** [comment]
The model used in this demo webapp is obtained from [White-box-Cartoonization](https://github.com/SystemErrorWang/White-box-Cartoonization/).
To change the style of the cartoon, you would need to develop your own dataset and follow the process for retraining as described in the original author's paper repo mentioned previously.
