### ISSUE TITLE
Our server hiccuped :/ Please upload another file! :) 

### ISSUE THREAD

**Issue by lcnwys** [experience-ml/cartoonize#8]
when i upload a fake .jpg to your website it show this message ,  how can i get the same effect?  
my website shows 
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
 - - [04/Jan/2021 11:20:21] "POST /cartoonize HTTP/1.1" 500 -

**Comment by nirajpandkar** [comment]
You'll have to add this at the start or in your main function - 

`app.config['SECRET_KEY'] = 'yourstrongsecretkey' `

Let me know how it works out :)
